sudo: required
language: java
language: kotlin
language: android
jdk:
- oraclejdk8
script:
- "./gradlew check"
- "./gradlew build"
before_install:
- chmod a+x gradlew
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21
