shallow_clone: true
clone_folder: c:\projects\lice-android

# From http://stackoverflow.com/a/31882307/2347774
# Hopefully prevent appveyor from building twice for PRs
branches:
  only:
    - master

# the basic outline for this install process is from
# github.com/googlesamples/android-ndk/blob/master/appveyor.yml
init:
  # prepare android-sdk
  - cd \
  - appveyor DownloadFile "http://dl.google.com/android/android-sdk_r24.4.1-windows.zip"
  - 7z x "android-sdk_r24.4.1-windows.zip" > nul
  - cd c:\projects\lice-android

install:
  # install android-sdk
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-25,platform-tools,tools,build-tools-25.0.1,build-tools-25.0.2,extra-google-m2repository,extra-android-m2repository,extra-android-support

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  ANDROID_HOME: C:\android-sdk-windows

build_script: gradlew assembleRelease --info

artifacts:
  - path: c:\projects\lice-android\app\build\outputs\apk\app-release-unsigned
    name: lice-android.jar
